"""add missing store columns

Revision ID: 7dd933600ef3
Revises: bba021409edf
Create Date: 2026-06-24 15:27:54.132128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd933600ef3'
down_revision: Union[str, Sequence[str], None] = 'bba021409edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('platform_domain', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('index_status', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('index_progress_percent', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('total_product_count', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('indexed_product_count', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('widget_config', sa.JSON(), nullable=True))
    op.add_column('stores', sa.Column('search_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'search_config')
    op.drop_column('stores', 'widget_config')
    op.drop_column('stores', 'indexed_product_count')
    op.drop_column('stores', 'total_product_count')
    op.drop_column('stores', 'index_progress_percent')
    op.drop_column('stores', 'index_status')
    op.drop_column('stores', 'platform_domain')
    # ### end Alembic commands ###
